### PR TITLE
Fix #759

### LINKED ISSUE #759: `tidy-NextBestNCRM` produces incorrect results
```
x <- NextBestNCRM(
     target = c(0.2, 0.35),
    overdose = c(0.75, 1.00),
    max_overdose_prob = 0.1
)

x |> tidy()
```

Produces no visible output.  But

```
class(x |> tidy())
[1] "tbl_NextBestNCRM" "tbl_df"           "tbl"              "data.frame" 
```
as expected.

  - [ ] Update tests to catch the error
  - [ ] Correct the method

### PR DESCRIPTION
**Pull request by Puzzled-Face**
closes #759

### CODE REVIEW

File: tests/testthat/test-Rules-methods.R [hunk 1]
```diff
@@ -4361,10 +4361,18 @@ test_that("tidy-IncrementsRelativeParts works correctly", {
   expect_snapshot_value(result, style = "deparse")
 })
 
+# Relevant:https://github.com/Roche/crmPack/issues/759
 test_that("tidy-NextBestNCRM works correctly", {
   obj <- .DefaultNextBestNCRM()
   result <- tidy(obj)
-  expect_snapshot_value(result, style = "deparse")
+  expected <- tibble::tibble(
```
Comment (danielinteractive) [inline tests/testthat/test-Rules-methods.R:4368]: ah yeah, so this is a good example where snapshot testing deceived us into thinking everything is fine

**Review by danielinteractive — APPROVED** [review]

File: tests/testthat/test-Rules-methods.R (hunk 1 above)
Comment (Puzzled-Face) [reply tests/testthat/test-Rules-methods.R:4368]: ... but also partly my fault for not checking the original snapshot to notice that its value was incorrect.  Subsequent snapshots passed because the incorrect value didn't change.  Human eyeball Mk 1 picked up the problem as soon as it appeared in real life.
