### PR TITLE
Closes #393

### LINKED ISSUE #393: Error in v_model_objects validates that [`OneParExpNormalPrior`] class slots are valid
After error correction #367 it turns out that the validity checks for the slots do not work as specified

https://github.com/Roche/crmPack/blob/8d913a71ebfab84df35e6fdd7aad0bbf694d8f0b/R/Model-validity.R#L511-L519

As far as I can see, the problem is that fixed sequence of 11 probs is generated to check if the inverse function is correct. The problem after merging #367 is that no NA are returned anymore, but the highest or lowest dose in case that the prob is outside of the range of the skeleton probs.
I think the check will now fail anytime when the fixed sequence does not match the skeleton probs. I think the following code will solve the problem:
```
# user specified values:
dose_grid <- 1:11
skel_probs <- seq(0.1, 0.5, length.out=11)

# just helper to test easily (not necessary in model-validity.r
skel_fun <- approxfun(x = dose_grid, y = skel_probs, rule = 2)
skel_fun_inv <- approxfun(x = skel_probs, y = dose_grid, rule = 2)

# new test code:
x <- skel_fun_inv(skel_probs) # Dose grid.
all.equal(skel_fun(x), skel_probs)
```

### PR DESCRIPTION
**Pull request by wwojciech**
Closes #393

### CODE REVIEW

**Review by danielinteractive — COMMENTED** [review]
looks good to me, would be good if @0liver0815 also tries it out interactively maybe

**Comment by wwojciech** [comment]
Hi @danielinteractive , @0liver0815 It is ready to review now. I cannot make assertion on `skel_probs` for uniqueness, as we do not have this ready in `assert_probabilities`. So I will first need to enhance `assert_probabilities` first and then add it here (this will be done within a separated issue https://github.com/Roche/crmPack/issues/397). But I think it is ok for now to proceed without it.

File: tests/testthat/test-Model-validity.R [hunk 1]
```diff
@@ -1079,14 +1079,14 @@ test_that("v_model_one_par_exp_normal_prior returns message for wrong skel_probs
   object@skel_probs <- c(-1, 0.5, Inf)
   expect_equal(
     v_model_one_par_exp_normal_prior(object),
-    "skel_probs must be sorted probability values between 0 and 1"
+    "skel_probs must be a unique sorted probability values between 0 and 1"
   )
 
   # Assigning not sorted skel_probs.
   object@skel_probs <- c(0.2, 0.1)
```
Comment (danielinteractive) [inline tests/testthat/test-Model-validity.R:1086]: what happens with `c(0.2, 0.2)`? is that caught?

Comment (wwojciech) [reply tests/testthat/test-Model-validity.R:1086]: Unfortunately not yet, as I have to enhance `assert_probabilities` to be able to check for the uniqueness. I just prepared these error messages already.

Comment (wwojciech) [reply tests/testthat/test-Model-validity.R:1086]: but maybe we can actually allow repeated values. The function will not be strictly incr. then, but since we have this interpolation - then it can be fine still. What do you think @danielinteractive ? Dose it make sense practically, that we have the same DLT prob for different doses?

Comment (danielinteractive) [reply tests/testthat/test-Model-validity.R:1086]: yeah but then it is not a bijective function?

Comment (wwojciech) [reply tests/testthat/test-Model-validity.R:1086]: Yeah, that is right, sorry I do not why I though that this wont be a problem with this interpolation. But this is obviously  wrong. So we have to add it.

Comment (wwojciech) [reply tests/testthat/test-Model-validity.R:1086]: Would it be ok if you accept it so that these unit tests errors disappear from the `main` and then I will work on the `assert_probabilities`? Tx!

Comment (danielinteractive) [reply tests/testthat/test-Model-validity.R:1086]: ok, just make a new issue for this then

**Review by danielinteractive — APPROVED** [review]

File: tests/testthat/test-Model-validity.R (hunk 1 above)
Comment (wwojciech) [reply tests/testthat/test-Model-validity.R:1086]: Sure, thanks. Created - https://github.com/Roche/crmPack/issues/399
