### PR TITLE
fix header

### LINKED ISSUE #777: `GeneralSimulationsSummary` @pengguanya

### PR DESCRIPTION
**Pull request by pengguanya**
# Pull Request

Fixes #777

### CODE REVIEW

File: R/Simulations-class.R [hunk 1]
```diff
@@ -286,49 +286,47 @@ DualSimulations <- function(rho_est,
...
+#' @description `r lifecycle::badge("stable")`
+#'
+#' This class captures the summary of general simulations output. Note that objects
+#' should not be created by users, therefore no initialization
+#' function is provided for this class.
+#'
+#' @slot target (`numeric`)\cr target toxicity interval
+#' @slot target_dose_interval (`numeric`)\cr corresponding target dose interval
+#' @slot nsim (`integer`)\cr number of simulations
+#' @slot prop_dlts (`ANY`)\cr proportions of DLTs in the trials
```
Comment (danielinteractive) [inline R/Simulations-class.R:300]: are you sure any type works here? I would guess it should be `numeric` or something specific?

File: R/Simulations-class.R [hunk 2]
```diff
@@ -286,49 +286,47 @@ DualSimulations <- function(rho_est,
...
+#' @slot mean_tox_risk (`numeric`)\cr mean toxicity risks for the patients
+#' @slot dose_selected (`numeric`)\cr doses selected as MTD
+#' @slot tox_at_doses_selected (`numeric`)\cr true toxicity at doses selected
+#' @slot prop_at_target (`numeric`)\cr Proportion of trials selecting target MTD
+#' @slot dose_most_selected (`numeric`)\cr dose most often selected as MTD
+#' @slot obs_tox_rate_at_dose_most_selected (`numeric`)\cr observed toxicity rate at dose most often selected
+#' @slot n_obs (`ANY`)\cr number of patients overall
```
Comment (danielinteractive) [inline R/Simulations-class.R:307]: same question here

File: R/Simulations-class.R (hunk 1 above)
Comment (danielinteractive) [reply R/Simulations-class.R:300]: note that the class in the S4 definition below can be more generic (e.g. here `ANY`) but we might have/need extra validation check for these which further restricts it and this should be the type listed here in the user documentation.

File: tests/testthat/test-Simulations-class.R [hunk 3]
```diff
@@ -181,3 +181,46 @@ test_that("DualSimulations user constructor arguments names are as expected", {
...
+# GeneralSimulationsSummary ----
+test_that("GeneralSimulationsSummary generates object correctly", {
+  target_value <- 1
+  target_dose_interval_value <- 2
+  nsim_value <- 3L
+  mean_tox_risk_value <- 4
+  dose_selected_value <- 5
+
+  result <- expect_silent(
+    new("GeneralSimulationsSummary",
```
Comment (danielinteractive) [inline tests/testthat/test-Simulations-class.R:194]: I would use here the internal constructor `.GeneralSimulationsSummary()` instead of `new`

File: R/Simulations-class.R (hunk 1 above)
Comment (danielinteractive) [reply R/Simulations-class.R:300]: ok in this case it is an abstract parent class. then I would not say anything here maybe about the type, or look at the child classes what they have in terms of type for these arguments

**Review by danielinteractive — COMMENTED** [review]
Thanks @pengguanya ! nice work, see minor questions on types below

File: R/Simulations-class.R (hunk 1 above)
Comment (pengguanya) [reply R/Simulations-class.R:300]: @danielinteractive Thanks for the comment. Looking into the downstream code. They (`nObs` and `propPLTs`) could be list, but they could also be numeric arrays in multi-dimensions. Below are the examples where they are arrays. But at somewhere else they could also be a one deferential list. I found no constrains or checks on exact type or even just dimensions. Only thing a bit more certain is their contents should be numeric, because there are computational operations (*, +, mean...) applied on them. Should I just add description that they could be numeric array or list and then keep the "ANY"? 
```
      ## number of patients overall
      if (object@data[[1]]@placebo) {
        nObs <- sapply(
          object@data,
          function(x) {
            data.frame(
              n.ACTV = sum(x@xLevel != 1L),
              n.PLCB = sum(x@xLevel == 1L)
            )
          }
        )
        nObs <- matrix(unlist(nObs), dim(nObs))
      } else {
```
```
          plotList[[plotIndex <- plotIndex + 1L]] <-
            h_barplot_percentages(
              x = x@propDLTs[1, ] * 100,
              description = "Proportion of DLTs [%] on active",
              xaxisround = 1
            )
        }
```

Comment (danielinteractive) [reply R/Simulations-class.R:300]: ok wow, thanks for digging into this and finding this. ok yeah let's do as you propose

File: R/Simulations-class.R (hunk 2 above)
Comment (danielinteractive) [reply R/Simulations-class.R:307]: can resolve similarly here, but I would hope that `n_obs` would always be a `count`?...

**Review by danielinteractive — APPROVED** [review]
